<?php

Class SettingsService
{

    public function getScript()
    {

        $data = [
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 1, 1, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 2, 2, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 3, 2, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 4, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 5, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 6, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 7, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 8, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 9, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 10, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 11, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 12, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 13, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 14, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 15, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 16, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 17, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 18, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 19, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 20, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 21, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 22, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 23, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 24, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 25, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 26, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 27, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 28, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 29, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 30, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 31, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 32, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 33, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 34, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 35, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 36, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 37, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 38, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 39, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 40, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 41, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 42, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 43, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 44, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 45, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 46, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 47, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 48, 2, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 49, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 50, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 51, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 52, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 53, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 54, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 55, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 56, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 57, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 58, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 59, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 60, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 61, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 62, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 63, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 64, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 65, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 66, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 67, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 68, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 69, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 70, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 71, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 72, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 73, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 74, 9, 1);"
        ];


        return $data;
    }



    public function getScriptVendedor()
    {
        $data = [
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 1, 1, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 2, 2, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 3, 2, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 4, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 5, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 6, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 7, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 8, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 9, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 10, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 11, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 12, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 13, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 14, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 15, 4, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 16, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 17, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 18, 4, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 19, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 20, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 21, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 22, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 23, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 24, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 25, 6, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 26, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 27, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 28, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 29, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 30, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 31, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 32, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 33, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 34, 7, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 35, 7, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 36, 7, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 37, 8, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 38, 8, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 39, 8, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 40, 8, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 41, 8, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 42, 8, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 43, 8, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 44, 8, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 45, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 46, 9, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 47, 9, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 48, 2, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 49, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 50, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 51, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 52, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 53, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 54, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 55, 6, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 56, 9, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 57, 9, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 58, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 59, 7, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 60, 7, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 61, 5, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 62, 5, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 63, 4, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 64, 4, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 65, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 66, 4, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 67, 4, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 68, 4, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 69, 5, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 70, 9, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 71, 7, 0);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 72, 9, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 73, 3, 1);",
                "INSERT INTO user_permiso (iduser, idsubmodulo, idmodulo, status) VALUES (??, 74, 9, 0);"
        ];


        return $data;
    }

}

?>
